### ISSUE TITLE
Does not work with strings as key_id and key_parent?

### ISSUE THREAD

**Issue by t-knapp** [DenQ/list-to-tree#18]
It seems, links / references do not work with string values.
Is this on purpose? Are there are some reasons?

`const list = [
    {
        _id: "EL",
        parentId: 0
    }, {
        _id: 2,
        parentId: "EL"
    }, {
        _id: 3,
        parentId: "EL"
    }
];

getTree() {
        const llt = new LLT(list, {
            key_id: '_id',
            key_parent: 'parentId'
        });
        return llt.GetTree();
    }`

Lib just gives warnings: 
![2018-06-22_165825](https://user-images.githubusercontent.com/6977154/41783596-8116cf14-763d-11e8-8a10-e4c4b2333608.png)

**Comment by DenQ** [comment]
Hello @t-knapp . Sorry, I was very busy.
Yes, string id, do not support.
Can be in future.
Thanks.

**Comment by t-knapp** [comment]
Thanks.

**Comment by karlitos** [comment]
Any news on that ? Seems to be like a quite important feature.

**Comment by NickStees** [comment]
Second the vote on this is useful!! Need to have parent and id's as strings not just integers

**Comment by NickStees** [comment]
For those interested, the [old version can sort by strings](https://github.com/DenQ/list-to-tree/blob/master/dist/old/list-to-tree.js)
