### ISSUE TITLE
Child key must be bigger than parent key

### ISSUE THREAD

**Issue by jesusisao** [DenQ/list-to-tree#27]
# Problem

When the child's ID is smaller than the parent's ID, the child may not be associated properly.
The reason is that there is code that sorts by parent ID, then sorts by ID, and adds to the tree.

## example

![before](https://user-images.githubusercontent.com/3109117/101275288-e2faea80-37e7-11eb-8bf9-ba1d0a6a1969.png)

# PR

I think you can solve this problem by sorting the list by the depth of the tree.

Here is a suggestion:
https://github.com/DenQ/list-to-tree/pull/26

**Comment by DenQ** [comment]
@jesusisao Hi. I will to look it in near days. Thanks you!

**Comment by DenQ** [comment]
Thanks! 💯
