### ISSUE TITLE
Mongodb find Search results Generate only a root node

### ISSUE THREAD

**Issue by xpsion** [DenQ/list-to-tree#9]
uMode.find({}, (err,data) => {
    let ltt = new LTT(data, {
        key_id: 'id',
        key_parent: 'parent'
      });
      let tree = ltt.GetTree();
      console.log(tree);
}

**Comment by DenQ** [comment]
@xpsion , What's in a date?
Give an example, please

**Comment by xpsion** [comment]
[{ "id" : 6000, "parent" : 0 }
{ "parent" : "6000", "id" : 6001 }
{ "parent" : "6000", "id" : 6002 }
{ "parent" : "6000", "id" : 6003 }
{ "parent" : "6000", "id" : 6004 }
{ "parent" : "6000", "id" : 6005 }
{ "parent" : "6000", "id" : 6006 }
{ "parent" : "6000", "id" : 6007 }
{ "id" : 6008, "parent" : 6001 }]

**Comment by xpsion** [comment]
data = JSON.parse(JSON.stringify(data));

Finally It Has Worked!

**Comment by DenQ** [comment]
@xpsion , I checked your `data` and created MR - https://github.com/DenQ/list-to-tree/pull/10
All working without convertation

**Comment by xpsion** [comment]
Strange, why use mongoose find results can not directly use
